## Features

= 

In [1]:
import pandas as pd
#from ydata_profiling import ProfileReport

In [2]:
columns_dipakai = ['Make',
                   'Modle',
                   'Year_from',
                   'Year_to',
                   'Body_type',
                   'number_of_cylinders',
                   'engine_type',
                   'engine_hp',
                   'engine_hp_rpm',
                   'transmission',
                   'mixed_fuel_consumption_per_100_km_l',
                   'fuel_tank_capacity_l',
                   'acceleration_0_100_km/h_s',
                   'max_speed_km_per_h',
                   'fuel_grade',
                   'battery_capacity_KW_per_h',
                   'charging_time_h',
                   'electric_range_km'
                   ]

In [3]:
#df = pd.read_csv('E:/Important/Machine-Learning/Dataset/Car Dataset 1945-2020.csv', usecols = columns_dipakai, low_memory=False)
df = pd.read_csv('Dataset/Car Dataset 1945-2020.csv', usecols = columns_dipakai, low_memory=False)

In [4]:
df.rename(columns = {'Modle':'Model'}, inplace = True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70823 entries, 0 to 70822
Data columns (total 18 columns):
 #   Column                               Non-Null Count  Dtype  
---  ------                               --------------  -----  
 0   Make                                 70823 non-null  object 
 1   Model                                70823 non-null  object 
 2   Year_from                            70586 non-null  float64
 3   Year_to                              70189 non-null  float64
 4   Body_type                            52252 non-null  object 
 5   number_of_cylinders                  59544 non-null  float64
 6   engine_type                          59878 non-null  object 
 7   engine_hp                            59877 non-null  float64
 8   engine_hp_rpm                        59408 non-null  object 
 9   transmission                         59842 non-null  object 
 10  mixed_fuel_consumption_per_100_km_l  40566 non-null  float64
 11  fuel_tank_capacity_l        

In [6]:
df

Make     Model  Year_from  Year_to  Body_type  number_of_cylinders  \
0       AC       ACE     1993.0   2000.0  Cabriolet                  8.0   
1       AC       ACE     1993.0   2000.0  Cabriolet                  8.0   
2       AC       ACE     1993.0   2000.0  Cabriolet                  8.0   
3       AC       ACE     1993.0   2000.0        NaN                  NaN   
4       AC       ACE     1993.0   2000.0        NaN                  NaN   
...    ...       ...        ...      ...        ...                  ...   
70818   ZX  Landmark     2007.0   2009.0        NaN                  NaN   
70819   ZX  Landmark     2007.0   2009.0        NaN                  NaN   
70820   ZX  Landmark     2007.0   2009.0        NaN                  NaN   
70821   ZX  Landmark     2007.0   2009.0        NaN                  NaN   
70822   ZX  Landmark     2007.0   2009.0        NaN                  NaN   

      engine_type  engine_hp engine_hp_rpm transmission  \
0        Gasoline      354.0          6500       Manual   
1        Gasoline      326.0          5800       Manual   
2        Gasoline      260.0          5250    Automatic   
3             NaN        NaN           NaN          NaN   
4             NaN        NaN           NaN          NaN   
...           ...        ...           ...          ...   
70818         NaN        NaN           NaN          NaN   
70819         NaN        NaN           NaN          NaN   
70820         NaN        NaN           NaN          NaN   
70821         NaN        NaN           NaN          NaN   
70822         NaN        NaN           NaN          NaN   

       mixed_fuel_consumption_per_100_km_l fuel_tank_capacity_l  \
0                                      NaN                   90   
1                                      NaN                   90   
2                                      8.0                   80   
3                                      NaN                  NaN   
4                                      NaN                  NaN   
...                                    ...                  ...   
70818                                  NaN                  NaN   
70819                                  NaN                  NaN   
70820                                  NaN                  NaN   
70821                                  NaN                  NaN   
70822                                  NaN                  NaN   

       acceleration_0_100_km/h_s max_speed_km_per_h fuel_grade  \
0                            5.0                250         95   
1                            5.0                250         98   
2                            NaN                225         95   
3                            NaN                NaN        NaN   
4                            NaN                NaN        NaN   
...                          ...                ...        ...   
70818                        NaN                NaN        NaN   
70819                        NaN                NaN        NaN   
70820                        NaN                NaN        NaN   
70821                        NaN                NaN        NaN   
70822                        NaN                NaN        NaN   

      battery_capacity_KW_per_h  electric_range_km charging_time_h  
0                           NaN                NaN             NaN  
1                           NaN                NaN             NaN  
2                           NaN                NaN             NaN  
3                           NaN                NaN             NaN  
4                           NaN                NaN             NaN  
...                         ...                ...             ...  
70818                       NaN                NaN             NaN  
70819                       NaN                NaN             NaN  
70820                       NaN                NaN             NaN  
70821                       NaN                NaN             NaN  
70822                      

In [7]:
df = df[df['battery_capacity_KW_per_h'].isna()]
df = df[df['charging_time_h'].isna()]
df = df[df['electric_range_km'].isna()]

In [8]:
df = df[df['Year_from'].notna()]
df = df[df['Year_to'].notna()]

In [9]:
df['year'] = df[['Year_from', 'Year_to']].mean(axis=1).round()

In [10]:
df['year'] = df['year'].astype(int)

In [11]:
df.drop(columns=['Year_from', 'Year_to', 'battery_capacity_KW_per_h', 'charging_time_h', 'electric_range_km'], inplace = True)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70170 entries, 0 to 70822
Data columns (total 14 columns):
 #   Column                               Non-Null Count  Dtype  
---  ------                               --------------  -----  
 0   Make                                 70170 non-null  object 
 1   Model                                70170 non-null  object 
 2   Body_type                            52252 non-null  object 
 3   number_of_cylinders                  59266 non-null  float64
 4   engine_type                          59599 non-null  object 
 5   engine_hp                            59598 non-null  float64
 6   engine_hp_rpm                        59130 non-null  object 
 7   transmission                         59563 non-null  object 
 8   mixed_fuel_consumption_per_100_km_l  40328 non-null  float64
 9   fuel_tank_capacity_l                 57583 non-null  object 
 10  acceleration_0_100_km/h_s            39958 non-null  float64
 11  max_speed_km_per_h               

In [13]:
df['Tipe_Mobil'] = df['Body_type'].replace({
    'Cabriolet': 'Sedan',
    'Coupe': 'Sedan',
    'Roadster': 'Sedan',
    'Sedan': 'Sedan',
    'Crossover': 'Jeep',
    'Hatchback': 'Sedan',
    'Liftback': 'Sedan',
    'Wagon': 'Sedan',
    'Minivan': 'Bus',
    'Fastback': 'Sedan',
    'Pickup': 'PickUp',
    'Targa': 'Sedan',
    'hardtop': 'Sedan',
    'Limousine': 'Bus',
    'Hatchback 3 doors': 'Sedan'
})
df.drop(columns=['Body_type'], inplace=True)

In [14]:
df.isna().sum()

Make                                       0
Model                                      0
number_of_cylinders                    10904
engine_type                            10571
engine_hp                              10572
engine_hp_rpm                          11040
transmission                           10607
mixed_fuel_consumption_per_100_km_l    29842
fuel_tank_capacity_l                   12587
acceleration_0_100_km/h_s              30212
max_speed_km_per_h                     27320
fuel_grade                             11713
year                                       0
Tipe_Mobil                             17918
dtype: int64

In [15]:
df.dropna(inplace=True)

In [16]:
df = df[df['year'] >= 2000]

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21457 entries, 9 to 70767
Data columns (total 14 columns):
 #   Column                               Non-Null Count  Dtype  
---  ------                               --------------  -----  
 0   Make                                 21457 non-null  object 
 1   Model                                21457 non-null  object 
 2   number_of_cylinders                  21457 non-null  float64
 3   engine_type                          21457 non-null  object 
 4   engine_hp                            21457 non-null  float64
 5   engine_hp_rpm                        21457 non-null  object 
 6   transmission                         21457 non-null  object 
 7   mixed_fuel_consumption_per_100_km_l  21457 non-null  float64
 8   fuel_tank_capacity_l                 21457 non-null  object 
 9   acceleration_0_100_km/h_s            21457 non-null  float64
 10  max_speed_km_per_h                   21457 non-null  object 
 11  fuel_grade                       

In [18]:
df['number_of_cylinders'].unique()

array([ 8.,  6.,  4.,  5.,  2., 12.,  3., 10.,  7., 16.])

In [19]:
df['number_of_cylinders'] = df['number_of_cylinders'].astype(int)

In [20]:
df['number_of_cylinders'].unique()

array([ 8,  6,  4,  5,  2, 12,  3, 10,  7, 16])

In [21]:
df['year'].unique()

array([2000, 2004, 2016, 2008, 2002, 2007, 2012, 2018, 2015, 2006, 2010,
       2001, 2014, 2017, 2019, 2009, 2011, 2003, 2013, 2020, 2005])

In [22]:
df['Tipe_Mobil'].unique()

array(['Sedan', 'Jeep', 'Bus', 'PickUp'], dtype=object)

## Tipe_Mobil
- Sedan = 0
- Jeep = 1
- Bus = 2
- PickUp = 3

In [23]:
df['Tipe_Mobil'] = df['Tipe_Mobil'].replace({
    'Sedan': 0,
    'Jeep': 1,
    'Bus': 2,
    'PickUp': 3
})

In [24]:
df['Tipe_Mobil'] = df['Tipe_Mobil'].astype(int)

In [25]:
df['Tipe_Mobil'].unique()

array([0, 1, 2, 3])

In [26]:
df

Make   Model  number_of_cylinders engine_type  engine_hp  \
9         AC   Aceca                    8    Gasoline      354.0   
11        AC   Aceca                    8    Gasoline      326.0   
54     Acura     MDX                    6    Gasoline      240.0   
60     Acura     MDX                    6    Gasoline      290.0   
68     Acura     NSX                    6    Gasoline      255.0   
...      ...     ...                  ...         ...        ...   
70756    ZAZ  Chance                    4    Gasoline       86.0   
70764    ZAZ    Sens                    4    Gasoline       70.0   
70765    ZAZ    Sens                    4    Gasoline       70.0   
70766    ZAZ    Vida                    4    Gasoline      109.0   
70767    ZAZ    Vida                    4    Gasoline      109.0   

      engine_hp_rpm transmission  mixed_fuel_consumption_per_100_km_l  \
9              6500       Manual                                 13.4   
11             5800       Manual                                 12.2   
54             5750    Automatic                                 13.2   
60             6200    Automatic                                 10.4   
68             6800       Manual                                 10.0   
...             ...          ...                                  ...   
70756          5800       Manual                                  6.7   
70764          5500       Manual                                  7.2   
70765          5500       Manual                                  7.2   
70766          5600       Manual                                  7.3   
70767          5600       Manual                                  7.8   

      fuel_tank_capacity_l  acceleration_0_100_km/h_s max_speed_km_per_h  \
9                       70                        5.6                250   
11                      70                        6.1                250   
54                      73                        8.7                190   
60                      73                        7.6                220   
68                      70                        5.0                260   
...                    ...                        ...                ...   
70756                   48                       12.5                172   
70764                   48                       17.0                162   
70765                   48                       17.0                162   
70766                   45                       11.5                170   
70767                   45                       11.5                170   

      fuel_grade  year  Tipe_Mobil  
9             95  2000           0  
11            98  2000           0  
54            92  2004           1  
60            95  2016           1  
68            95  2004           0  
...          ...   ...         ...  
70756         92  2014           0  
70764         95  2014           0  
70765         95  2014           0  
70766         95  2016           0  
70767         95  2016           0  

[21457 rows x 14 columns]

In [27]:
not_used = ['Hybrid', 'Gasoline, Electric', 'Diesel, Hybrid']
df = df[~df['engine_type'].isin(not_used)]

In [28]:
df['engine_type'] = df['engine_type'].replace({
    'Gasoline, Gas': 'Gasoline',
    'Gas': 'Gasoline',
})

C:\Users\akane\AppData\Local\Temp\ipykernel_18732\1321999188.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['engine_type'] = df['engine_type'].replace({


In [29]:
df['engine_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

Tipe Bensin
- Gasoline = 0
- Diesel = 1

In [30]:
df.loc[:,'engine_type'] = df['engine_type'].replace({
    'Gasoline': 0,
    'Diesel': 1,
})

In [31]:
df['engine_type'].unique()

array([0, 1], dtype=object)

In [32]:
df['engine_type'] = df['engine_type'].astype(int)

C:\Users\akane\AppData\Local\Temp\ipykernel_18732\1707576425.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['engine_type'] = df['engine_type'].astype(int)


In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21242 entries, 9 to 70767
Data columns (total 14 columns):
 #   Column                               Non-Null Count  Dtype  
---  ------                               --------------  -----  
 0   Make                                 21242 non-null  object 
 1   Model                                21242 non-null  object 
 2   number_of_cylinders                  21242 non-null  int32  
 3   engine_type                          21242 non-null  int32  
 4   engine_hp                            21242 non-null  float64
 5   engine_hp_rpm                        21242 non-null  object 
 6   transmission                         21242 non-null  object 
 7   mixed_fuel_consumption_per_100_km_l  21242 non-null  float64
 8   fuel_tank_capacity_l                 21242 non-null  object 
 9   acceleration_0_100_km/h_s            21242 non-null  float64
 10  max_speed_km_per_h                   21242 non-null  object 
 11  fuel_grade                       

In [34]:
not_used1 = ['Ethanol', '80']
df = df[~df['fuel_grade'].isin(not_used1)]

In [35]:
df['fuel_grade'].unique()

array(['95', '98', '92', 'diesel', '95, 92', '98, 95', 'Gasoline', 'Gas',
       '95, Ethanol', '98, 95, 92', '95, Gas', '92, Ethanol',
       'Gasoline, Gas', '98, Ethanol', '92, Gas', '98, Gas',
       '95, 92, Gas', '98, 95, Gas', '98, 95, 92, Ethanol'], dtype=object)

Octance Number
- Diesel = 50 = **0**
- Gasoline = Pertalite = 90 = **1**
- Pertamax = 92 = **2**
- Pertamax Plus = 92 to 98 = **3**

In [36]:
df['fuel_grade'] = df['fuel_grade'].replace({
    '95': '3',
    '92': '2',
    '98': '3',
    'diesel': '0',
    '95, 92': '2',
    '98, 95': '3',
    'Gasoline': '1',
    'Gas': '1',
    '95, Ethanol': '3',
    '98, 95, 92': '3',
    '95, Gas': '3',
    '92, Ethanol': '3',
    'Gasoline, Gas': '1',
    '92, Gas': '2',
    '98, Gas': '3',
    '95, 92, Gas': '2',
    '98, 95, Gas': '3',
    '98, 95, 92, Ethanol': '3',
    '98, Ethanol': '3'
})

In [37]:
df['fuel_grade'].unique()

array(['3', '2', '0', '1'], dtype=object)

In [38]:
df['fuel_grade'] = df['fuel_grade'].astype(int)

In [39]:
df['max_speed_km_per_h'] = df['max_speed_km_per_h'].str.replace(',', '.').astype(float).astype(int)


In [40]:
df['max_speed_km_per_h'] = df['max_speed_km_per_h'].astype(int).round()

In [41]:
df['fuel_tank_capacity_l'] = df['fuel_tank_capacity_l'].str.replace(',', '.').astype(float).astype(int)

In [42]:
df['engine_hp_rpm'] = df['engine_hp_rpm'].astype(int)

In [43]:
df['transmission'].unique()

array(['Manual', 'Automatic', 'robot',
       'Continuously variable transmission (CVT)'], dtype=object)

Tipe Transmisi
- Automatic = 0
- Manual = 1

In [44]:
not_used2 = ['robot', 'Continuously variable transmission (CVT)']
df = df[~df['transmission'].isin(not_used2)]

In [45]:
df['transmission'] = df['transmission'].replace({
    'Manual': '1',
    'Automatic': '0'
    })

In [46]:
df['transmission'] = df['transmission'].astype(int)

In [47]:
df['transmission'].unique()

array([1, 0])

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18595 entries, 9 to 70767
Data columns (total 14 columns):
 #   Column                               Non-Null Count  Dtype  
---  ------                               --------------  -----  
 0   Make                                 18595 non-null  object 
 1   Model                                18595 non-null  object 
 2   number_of_cylinders                  18595 non-null  int32  
 3   engine_type                          18595 non-null  int32  
 4   engine_hp                            18595 non-null  float64
 5   engine_hp_rpm                        18595 non-null  int32  
 6   transmission                         18595 non-null  int32  
 7   mixed_fuel_consumption_per_100_km_l  18595 non-null  float64
 8   fuel_tank_capacity_l                 18595 non-null  int32  
 9   acceleration_0_100_km/h_s            18595 non-null  float64
 10  max_speed_km_per_h                   18595 non-null  int32  
 11  fuel_grade                       

In [49]:
df

Make   Model  number_of_cylinders  engine_type  engine_hp  \
9         AC   Aceca                    8            0      354.0   
11        AC   Aceca                    8            0      326.0   
54     Acura     MDX                    6            0      240.0   
60     Acura     MDX                    6            0      290.0   
68     Acura     NSX                    6            0      255.0   
...      ...     ...                  ...          ...        ...   
70756    ZAZ  Chance                    4            0       86.0   
70764    ZAZ    Sens                    4            0       70.0   
70765    ZAZ    Sens                    4            0       70.0   
70766    ZAZ    Vida                    4            0      109.0   
70767    ZAZ    Vida                    4            0      109.0   

       engine_hp_rpm  transmission  mixed_fuel_consumption_per_100_km_l  \
9               6500             1                                 13.4   
11              5800             1                                 12.2   
54              5750             0                                 13.2   
60              6200             0                                 10.4   
68              6800             1                                 10.0   
...              ...           ...                                  ...   
70756           5800             1                                  6.7   
70764           5500             1                                  7.2   
70765           5500             1                                  7.2   
70766           5600             1                                  7.3   
70767           5600             1                                  7.8   

       fuel_tank_capacity_l  acceleration_0_100_km/h_s  max_speed_km_per_h  \
9                        70                        5.6                 250   
11                       70                        6.1                 250   
54                       73                        8.7                 190   
60                       73                        7.6                 220   
68                       70                        5.0                 260   
...                     ...                        ...                 ...   
70756                    48                       12.5                 172   
70764                    48                       17.0                 162   
70765                    48                       17.0                 162   
70766                    45                       11.5                 170   
70767                    45                       11.5                 170   

       fuel_grade  year  Tipe_Mobil  
9               3  2000           0  
11              3  2000           0  
54              2  2004           1  
60              3  2016           1  
68              3  2004           0  
...           ...   ...         ...  
70756           2  2014           0  
70764           3  2014           0  
70765           3  2014           0  
70766           3  2016           0  
70767           3  2016           0  

[18595 rows x 14 columns]

# Model Creation

Coba2 buat model (pake feature column) make feature data:
- number of cylinder (category)
- engine type (category)
- engine hp (number)
- engine hp rpm (number)
- transmission (category)
- acceleration_0_100_km/h_s (number)
- fuel_grade (category)
- mixed_fuel_consumption_per_100_km_l (target)

In [50]:
#Import library
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow import feature_column
import pandas as pd

In [51]:
#Required features for training ? (tentative)
req_feat = ['number_of_cylinders',
            'engine_type',
            'engine_hp',
            'engine_hp_rpm',
            'transmission',
            'acceleration_0_100_km/h_s',
            'fuel_grade',
            'mixed_fuel_consumption_per_100_km_l']

target = 'mixed_fuel_consumption_per_100_km_l'

#Data for train
data = df[req_feat]

In [52]:
#Data split into val and train set
train, val = train_test_split(data, test_size=0.1)
print(f'Number of training datasets: {len(train)}')
print(f'Number of validation datasets: {len(val)}')

Number of training datasets: 16735
Number of validation datasets: 1860


In [53]:
#Function to Convert pd dataframe to tensorflow datasets
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop(target)
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size).prefetch(tf.data.experimental.AUTOTUNE)
  return ds

In [54]:
#Converting train and val pandas dataframe to Tensorflow datasets
train_set = df_to_dataset(train, shuffle=True, batch_size=32)
val_set = df_to_dataset(val, shuffle=False, batch_size=32)

In [55]:
#Function to create feature layer
def feature_creation():
  num_cylinder = feature_column.categorical_column_with_vocabulary_list('number_of_cylinders', df['number_of_cylinders'].unique())
  num_cylinder = feature_column.indicator_column(num_cylinder)
  engine_type = feature_column.categorical_column_with_vocabulary_list('engine_type', df['engine_type'].unique())
  engine_type = feature_column.indicator_column(engine_type)
  transmission = feature_column.categorical_column_with_vocabulary_list('transmission', df['transmission'].unique())
  transmission = feature_column.indicator_column(transmission)
  fuel_grade = feature_column.categorical_column_with_vocabulary_list('fuel_grade', df['fuel_grade'].unique())
  fuel_grade  = feature_column.indicator_column(fuel_grade )
  engine_hp = feature_column.numeric_column('engine_hp')
  engine_hp_rpm = feature_column.numeric_column('engine_hp_rpm')
  acceleration = feature_column.numeric_column('acceleration_0_100_km/h_s')
  feature_columns = [
      num_cylinder,
      engine_type,
      transmission,
      fuel_grade,
      engine_hp,
      engine_hp_rpm,
      acceleration
  ]
  feature_layer = tf.keras.layers.DenseFeatures(feature_columns)

  return feature_layer 

In [58]:
#Create model and train
feature_layer = feature_creation()

model = tf.keras.Sequential([
  feature_layer,
  tf.keras.layers.Dense(1)
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss='mse',
              metrics=['mae'])

model.fit(train_set,
          validation_data=val_set,
          epochs=20)

Epoch 1/20


523/523 [==============================] - 2s 2ms/step - loss: 18615.8613 - mae: 63.8598 - val_loss: 66.8177 - val_mae: 6.1301
Epoch 2/20
523/523 [==============================] - 1s 2ms/step - loss: 53.5259 - mae: 5.4064 - val_loss: 41.0291 - val_mae: 4.7776
Epoch 3/20
523/523 [==============================] - 1s 2ms/step - loss: 30.0663 - mae: 4.0753 - val_loss: 20.9781 - val_mae: 3.4578
Epoch 4/20
523/523 [==============================] - 1s 2ms/step - loss: 14.6050 - mae: 2.8998 - val_loss: 10.0404 - val_mae: 2.4008
Epoch 5/20
523/523 [==============================] - 1s 2ms/step - loss: 7.3577 - mae: 2.0986 - val_loss: 5.7964 - val_mae: 1.8767
Epoch 6/20
523/523 [==============================] - 1s 2ms/step - loss: 4.9365 - mae: 1.7458 - val_loss: 4.5863 - val_mae: 1.6725
Epoch 7/20
523/523 [==============================] - 1s 2ms/step - loss: 4.2724 - mae: 1.6277 - val_loss: 4.1874 - val_mae: 1.5949
Epoch 8/20
523/523 [==============================] - 1s 2ms/step - loss: 3

In [59]:
data_test = [[8, 0, 0, 2, 381, 5600, 6.7]] #Toyota Sequioa
data_test = pd.DataFrame(data_test, columns=['number_of_cylinders', 
                                                            'engine_type',
                                                            'transmission',
                                                            'fuel_grade',
                                                            'engine_hp',
                                                            'engine_hp_rpm',
                                                            'acceleration_0_100_km/h_s'])
data_test= tf.data.Dataset.from_tensor_slices((dict(data_test)))
data_test = data_test.batch(1)
hasil = model.predict(data_test)
print(hasil)

1/1 [==============================] - 0s 176ms/step
[[13.280671]]


## Model Creation 2

Fitur yg dipake msh sama, cuma gk pake feature column (Though, masih bingung one-hotnya kek gmna)

In [57]:
#Directly create train and val dataset without feature column
train_label = train.pop('mixed_fuel_consumption_per_100_km_l')
train_data = tf.data.Dataset.from_tensor_slices((train.values, train_label.values))
val_label = val.pop('mixed_fuel_consumption_per_100_km_l')
val_data = tf.data.Dataset.from_tensor_slices((val.values, val_label.values))

In [58]:
#Batches and shuffles (for train only) the data
train_data = train_data.shuffle(10).batch(32)
val_data = val_data.batch(32)

In [59]:
#Create model and train
model = tf.keras.Sequential([
  tf.keras.layers.Dense(128, activation='relu', input_shape=(7,)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(.1),
  tf.keras.layers.Dense(1)
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss='mse',
              metrics=['mae'])

model.fit(train_data,
          validation_data=val_data,
          epochs=20)

Epoch 1/20


523/523 [==============================] - 3s 3ms/step - loss: 221.0124 - mae: 5.7525 - val_loss: 4.0930 - val_mae: 1.4757
Epoch 2/20
523/523 [==============================] - 1s 2ms/step - loss: 4.7983 - mae: 1.6319 - val_loss: 3.7568 - val_mae: 1.4421
Epoch 3/20
523/523 [==============================] - 1s 2ms/step - loss: 4.7537 - mae: 1.6267 - val_loss: 3.8772 - val_mae: 1.4386
Epoch 4/20
523/523 [==============================] - 1s 2ms/step - loss: 4.6505 - mae: 1.6094 - val_loss: 3.6772 - val_mae: 1.4063
Epoch 5/20
523/523 [==============================] - 1s 2ms/step - loss: 4.4818 - mae: 1.5801 - val_loss: 3.4173 - val_mae: 1.3735
Epoch 6/20
523/523 [==============================] - 1s 2ms/step - loss: 4.6164 - mae: 1.6052 - val_loss: 4.0367 - val_mae: 1.4803
Epoch 7/20
523/523 [==============================] - 1s 2ms/step - loss: 4.5901 - mae: 1.6022 - val_loss: 3.8063 - val_mae: 1.4377
Epoch 8/20
523/523 [==============================] - 1s 3ms/step - loss: 4.4663 - ma